### ISSUE TITLE
Main Window Display

### ISSUE THREAD

**Issue by cgrooves** [cgrooves/black-earth#3]
Make the main game display window where we can see sky and ground (they don't have to actually be interact-able, just create a visual backdrop for the game).

**Comment by TheSpy0** [comment]
What would be an acceptable resolution for the window? Keep it true to Scorced Earth, or add higher resolution options?

**Comment by cgrooves** [comment]
> What would be an acceptable resolution for the window? Keep it true to Scorced Earth, or add higher resolution options?

I'm not sure; I've never really got the hang of resolutions, and 2D graphics, this will be new for me. I think that this partly ties into whether we want to try and make a real clone as in "same graphics and everything, same features, just reimplemented on a newer platform", or more of a loose copy of "same gameplay and style but updated graphics and some updated mechanics". What're your thoughts?

I'm kind of in favor of updating resolution/graphics to something a bit more modern, though another driving factor is I'm not really a graphics guy and I don't want to spend a lot of time making/getting nice graphics, so maybe lower res stuff is better.

**Comment by cgrooves** [comment]
For now, let's just do whatever keeps this project moving forward.
