### ISSUE TITLE
Player Turns

### ISSUE THREAD

**Issue by cgrooves** [cgrooves/black-earth#9]
The players can take turns firing the projectile at each other. Back-and-forth, back-and-forth.

__Acceptance Criteria:__
- Game play is now that players can take turns firing projectiles at each other
- Some visual indicator of whose turn it is

**Comment by TheSpy0** [comment]
Would be interested in having a "real-time mode" where players are able to fire without passing turns. This can be added later on.

**Comment by cgrooves** [comment]
Yeah; I think if we're smart, we can encapsulate the turn dynamics to allow for multiple configurations for how to play:
- Sequential (one at a time, one shot at a time)
- Sequential (one player at a time, all shots fired at the same time)
- Continuous (keep firing and keep updating)
